spring:
  cloud:
    bus:
      enabled: false
  sleuth:
    stream:
      enabled: false
  datasource:
    password: password
    url: jdbc:mysql://47.98.67.176:3306
    username: root
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration,org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
hystrix:
  stream:
    queue:
      enabled: false
data:
  dir: src/main/resources
eureka:
  client:
    enabled: false
