/**
 * 钉钉API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.choerodon.devops.infra.dingtalk.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * 部门对象
 */
@ApiModel(description = "部门对象")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-14T17:49:16.234+08:00")
public class Department   {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("parentid")
  private String parentid = null;

  @JsonProperty("createDeptGroup")
  private Boolean createDeptGroup = null;

  @JsonProperty("autoAddUser")
  private Boolean autoAddUser = null;

  public Department id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * 部门id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "部门id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Department name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 部门名称
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "部门名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Department parentid(String parentid) {
    this.parentid = parentid;
    return this;
  }

   /**
   * 父部门id，根部门为1
   * @return parentid
  **/
  @ApiModelProperty(example = "null", value = "父部门id，根部门为1")
  public String getParentid() {
    return parentid;
  }

  public void setParentid(String parentid) {
    this.parentid = parentid;
  }

  public Department createDeptGroup(Boolean createDeptGroup) {
    this.createDeptGroup = createDeptGroup;
    return this;
  }

   /**
   * 是否同步创建一个关联此部门的企业群, true表示是, false表示不是 
   * @return createDeptGroup
  **/
  @ApiModelProperty(example = "null", value = "是否同步创建一个关联此部门的企业群, true表示是, false表示不是 ")
  public Boolean getCreateDeptGroup() {
    return createDeptGroup;
  }

  public void setCreateDeptGroup(Boolean createDeptGroup) {
    this.createDeptGroup = createDeptGroup;
  }

  public Department autoAddUser(Boolean autoAddUser) {
    this.autoAddUser = autoAddUser;
    return this;
  }

   /**
   * 当群已经创建后，是否有新人加入部门会自动加入该群, true表示是, false表示不是 
   * @return autoAddUser
  **/
  @ApiModelProperty(example = "null", value = "当群已经创建后，是否有新人加入部门会自动加入该群, true表示是, false表示不是 ")
  public Boolean getAutoAddUser() {
    return autoAddUser;
  }

  public void setAutoAddUser(Boolean autoAddUser) {
    this.autoAddUser = autoAddUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Department department = (Department) o;
    return Objects.equals(this.id, department.id) &&
        Objects.equals(this.name, department.name) &&
        Objects.equals(this.parentid, department.parentid) &&
        Objects.equals(this.createDeptGroup, department.createDeptGroup) &&
        Objects.equals(this.autoAddUser, department.autoAddUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parentid, createDeptGroup, autoAddUser);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Department {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentid: ").append(toIndentedString(parentid)).append("\n");
    sb.append("    createDeptGroup: ").append(toIndentedString(createDeptGroup)).append("\n");
    sb.append("    autoAddUser: ").append(toIndentedString(autoAddUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

