/**
 * 钉钉API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.choerodon.devops.infra.dingtalk.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * 消息体
 */
@ApiModel(description = "消息体")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-14T17:49:16.234+08:00")
public class Link   {
  @JsonProperty("messageUrl")
  private String messageUrl = null;

  @JsonProperty("picUrl")
  private String picUrl = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("text")
  private String text = null;

  public Link messageUrl(String messageUrl) {
    this.messageUrl = messageUrl;
    return this;
  }

   /**
   * 消息点击链接地址
   * @return messageUrl
  **/
  @ApiModelProperty(example = "null", value = "消息点击链接地址")
  public String getMessageUrl() {
    return messageUrl;
  }

  public void setMessageUrl(String messageUrl) {
    this.messageUrl = messageUrl;
  }

  public Link picUrl(String picUrl) {
    this.picUrl = picUrl;
    return this;
  }

   /**
   * 图片媒体文件id，可以调用上传媒体文件接口获取
   * @return picUrl
  **/
  @ApiModelProperty(example = "null", value = "图片媒体文件id，可以调用上传媒体文件接口获取")
  public String getPicUrl() {
    return picUrl;
  }

  public void setPicUrl(String picUrl) {
    this.picUrl = picUrl;
  }

  public Link title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 消息标题
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "消息标题")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Link text(String text) {
    this.text = text;
    return this;
  }

   /**
   * 消息描述
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "消息描述")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Link link = (Link) o;
    return Objects.equals(this.messageUrl, link.messageUrl) &&
        Objects.equals(this.picUrl, link.picUrl) &&
        Objects.equals(this.title, link.title) &&
        Objects.equals(this.text, link.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageUrl, picUrl, title, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Link {\n");

    sb.append("    messageUrl: ").append(toIndentedString(messageUrl)).append("\n");
    sb.append("    picUrl: ").append(toIndentedString(picUrl)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

