/**
 * 钉钉API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.choerodon.devops.infra.dingtalk.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * message @
 */
@ApiModel(description = "message @")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-14T17:49:16.234+08:00")
public class MessageAt   {
  @JsonProperty("atMobiles")
  private List<String> atMobiles = new ArrayList<String>();

  @JsonProperty("isAtAll")
  private Boolean isAtAll = null;

  public MessageAt atMobiles(List<String> atMobiles) {
    this.atMobiles = atMobiles;
    return this;
  }

  public MessageAt addAtMobilesItem(String atMobilesItem) {
    this.atMobiles.add(atMobilesItem);
    return this;
  }

   /**
   * Get atMobiles
   * @return atMobiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAtMobiles() {
    return atMobiles;
  }

  public void setAtMobiles(List<String> atMobiles) {
    this.atMobiles = atMobiles;
  }

  public MessageAt isAtAll(Boolean isAtAll) {
    this.isAtAll = isAtAll;
    return this;
  }

   /**
   * Get isAtAll
   * @return isAtAll
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsAtAll() {
    return isAtAll;
  }

  public void setIsAtAll(Boolean isAtAll) {
    this.isAtAll = isAtAll;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageAt messageAt = (MessageAt) o;
    return Objects.equals(this.atMobiles, messageAt.atMobiles) &&
        Objects.equals(this.isAtAll, messageAt.isAtAll);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atMobiles, isAtAll);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageAt {\n");

    sb.append("    atMobiles: ").append(toIndentedString(atMobiles)).append("\n");
    sb.append("    isAtAll: ").append(toIndentedString(isAtAll)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

