/**
 * 钉钉API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.choerodon.devops.infra.dingtalk.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * 部门用户列表返回结果
 */
@ApiModel(description = "部门用户列表返回结果")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-14T17:49:16.234+08:00")
public class UserListResult extends Result  {
  @JsonProperty("hasMore")
  private Boolean hasMore = null;

  @JsonProperty("userlist")
  private List<User> userlist = new ArrayList<User>();

  public UserListResult hasMore(Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

   /**
   * 在分页查询时返回，代表是否还有下一页更多数据
   * @return hasMore
  **/
  @ApiModelProperty(example = "null", value = "在分页查询时返回，代表是否还有下一页更多数据")
  public Boolean getHasMore() {
    return hasMore;
  }

  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }

  public UserListResult userlist(List<User> userlist) {
    this.userlist = userlist;
    return this;
  }

  public UserListResult addUserlistItem(User userlistItem) {
    this.userlist.add(userlistItem);
    return this;
  }

   /**
   * 成员列表
   * @return userlist
  **/
  @ApiModelProperty(example = "null", value = "成员列表")
  public List<User> getUserlist() {
    return userlist;
  }

  public void setUserlist(List<User> userlist) {
    this.userlist = userlist;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserListResult userListResult = (UserListResult) o;
    return Objects.equals(this.hasMore, userListResult.hasMore) &&
        Objects.equals(this.userlist, userListResult.userlist) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMore, userlist, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserListResult {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    userlist: ").append(toIndentedString(userlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

